#!/usr/bin/python

import re

def linkName(match):
  return 'problem%03d' % int(match.group(1))

def getPost(lines):
  "Return certain post information from an array of lines."
  for i,line in enumerate(lines):
    if line[:5] == 'TITLE':
      title = line[7:-1]
    if line[:8] == 'CATEGORY':
      category = line[10:-1]
    if line[:4] == 'DATE':
      date = line[6:-1]
    if line[:4] == 'BODY':
      bodyStart = i + 1
    if line[:13] == 'EXTENDED BODY':
      bodyEnd = i - 1
  body = 'Lines %d to %d' % (bodyStart, bodyEnd)
  body = ''.join(lines[bodyStart:bodyEnd])
  body = body.replace('http://www.leancrew.com/mechanics/', '')
  body = body.replace('/mechanics/images/', 'images/')
  body = re.sub(r'chapter_(?:\d+)\/problem_(\d+)', linkName, body)
  body = body.replace('\\\\','\\')
  body = body.replace(' class="c"', '')
  return (title, date, category, body)


orig = file('problems.txt')

nextline = orig.readline()
while nextline != "":
  lines = []
  while nextline != "--------\n":
    lines.append(nextline)
    nextline = orig.readline()
  
  (title, date, category, body) = getPost(lines)
  chapter = '%2d' % int(category.split()[1])
  problem = int(title.split()[1])
  
  filename = 'src/problem%03d.md' % problem
  md = file(filename, 'w')
  md.write('\n'.join(['# %s #' % title, '', body]))
  md.close()
  nextline= orig.readline()

orig.close()

